; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

[env:esp32-c6-devkitc-1]
platform = https://github.com/pioarduino/platform-espressif32/releases/download/stable/platform-espressif32.zip
board = esp32-c6-devkitc-1
board_build.partitions = huge_app.csv
framework = arduino
lib_deps = 
	adafruit/Adafruit NeoPixel@^1.15.1
	adafruit/RTClib@^2.1.4
	arduino-libraries/NTPClient@^3.2.1
	adafruit/Adafruit GFX Library@^1.12.3
	adafruit/Adafruit SSD1306@^2.5.15
    jgromes/RadioLib@^7.3.0
build_flags = 
	-DARDUINO_USB_MODE=1
	-DARDUINO_USB_CDC_ON_BOOT=1    
	-DSSD1306_NO_SPLASH=1
    -DRADIOLIB_EXCLUDE_AFSK=1
    -DRADIOLIB_EXCLUDE_APRS=1
    -DRADIOLIB_EXCLUDE_AX25=1
    -DRADIOLIB_EXCLUDE_BELL=1
    -DRADIOLIB_EXCLUDE_CC1101=1
    -DRADIOLIB_EXCLUDE_DIRECT_RECEIVE=1
    -DRADIOLIB_EXCLUDE_FSK4=1
    -DRADIOLIB_EXCLUDE_HELLSCHREIBER=1
    -DRADIOLIB_EXCLUDE_LORAWAN=1
    -DRADIOLIB_EXCLUDE_LR11X0=1
    -DRADIOLIB_EXCLUDE_MORSE=1
    -DRADIOLIB_EXCLUDE_NRF24=1
    -DRADIOLIB_EXCLUDE_PAGER=1
    -DRADIOLIB_EXCLUDE_RF69=1
    -DRADIOLIB_EXCLUDE_RFM2X=1
    -DRADIOLIB_EXCLUDE_RTTY=1
    -DRADIOLIB_EXCLUDE_SI443X=1
    -DRADIOLIB_EXCLUDE_SSTV=1
    -DRADIOLIB_EXCLUDE_SX1231=1
    ;-DRADIOLIB_EXCLUDE_SX126X=1
    -DRADIOLIB_EXCLUDE_SX127X=1
    -DRADIOLIB_EXCLUDE_SX128X=1
