# System settingsp
CONFIG_BOOT_BANNER=y
CONFIG_POSIX_API=y
CONFIG_PICOLIBC=y
CONFIG_PICOLIBC_IO_FLOAT=y
CONFIG_CBPRINTF_LIBC_SUBSTS=y
CONFIG_CBPRINTF_FP_SUPPORT=y
CONFIG_REBOOT=y
CONFIG_USB_CDC_ACM=y
CONFIG_ENTROPY_GENERATOR=y
CONFIG_SYSTEM_WORKQUEUE_STACK_SIZE=4096

# Peripherals
CONFIG_I2C=y
CONFIG_SPI=y
CONFIG_DISPLAY=y
CONFIG_RTC=y
CONFIG_SERIAL=y
CONFIG_UART_LINE_CTRL=y
CONFIG_LORA=y

# Logging 
CONFIG_CONSOLE=y
CONFIG_UART_CONSOLE=y
CONFIG_LOG=y
CONFIG_LOG_MODE_IMMEDIATE=y

# LVGL (UI)
CONFIG_LVGL=y
CONFIG_LV_CONF_MINIMAL=y
CONFIG_LV_Z_VDB_SIZE=100
CONFIG_LV_Z_MEM_POOL_SIZE=16384

CONFIG_LV_DPI_DEF=32
CONFIG_LV_Z_COLOR_MONO_HW_INVERSION=y
CONFIG_LV_COLOR_DEPTH_1=y

CONFIG_LV_USE_LOG=y
CONFIG_LV_USE_LABEL=y
CONFIG_LV_USE_TEXTAREA=y
CONFIG_LV_USE_IMAGE=y
CONFIG_LV_USE_FLEX=y
CONFIG_LV_FONT_UNSCII_8=y
CONFIG_LV_FONT_UNSCII_16=y

# Settings
CONFIG_SETTINGS=y
CONFIG_SETTINGS_NVS=y
CONFIG_NVS=y
CONFIG_FLASH=y
CONFIG_FLASH_MAP=y

# WDT
CONFIG_TASK_WDT=y

# Wi-Fi Configuration
CONFIG_WIFI=y
CONFIG_NET_L2_WIFI_MGMT=y
CONFIG_NET_L2_ETHERNET=y
CONFIG_NETWORKING=y
CONFIG_NET_DHCPV4=y
CONFIG_NET_IPV4=y
CONFIG_NET_TCP=y
CONFIG_SNTP=y
CONFIG_DNS_RESOLVER=y
CONFIG_WIFI_CREDENTIALS=y

# HTTP
CONFIG_NET_SOCKETS=y
CONFIG_HTTP_CLIENT=y
CONFIG_BASE64=y

# Shell
CONFIG_SHELL=y
CONFIG_SHELL_BACKEND_SERIAL=y
CONFIG_DEVICE_SHELL=n
CONFIG_DEVMEM_SHELL=n
CONFIG_KERNEL_SHELL=n
CONFIG_NET_L2_WIFI_SHELL=y
CONFIG_WIFI_CREDENTIALS_SHELL=y
CONFIG_SHELL_WILDCARD=n

# Detailed log configuration
# CONFIG_NET_LOG=y
# CONFIG_WIFI_LOG_LEVEL_DBG=y
# CONFIG_WIFI_NM_LOG_LEVEL_DBG=y
# CONFIG_NET_L2_WIFI_MGMT_LOG_LEVEL_DBG=y
# CONFIG_NET_MGMT_EVENT_LOG_LEVEL_DBG=y
# CONFIG_NET_CONFIG_LOG_LEVEL_DBG=y
# CONFIG_NET_CONNECTION_MANAGER_LOG_LEVEL_DBG=y
# CONFIG_NET_CORE_LOG_LEVEL_DBG=y
# CONFIG_NET_IF_LOG_LEVEL_DBG=y
# CONFIG_LV_USE_LOG=y
# CONFIG_DISPLAY_LOG_LEVEL_WRN=y
